spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: books
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      schema-locations: schema.sql
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

  h2:
    console:
      enabled: true
      path: /h2-console

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: INFO
    Batch: INFO
    ru.otus.hw: DEBUG
